"""add_quality_fields_to_jobs

Revision ID: 2186ad0aad53
Revises: 07199a478798
Create Date: 2026-04-27 13:26:22.039295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2186ad0aad53'
down_revision: Union[str, Sequence[str], None] = '07199a478798'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('external_id', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column('dedup_hash', sa.String(length=64), nullable=True))
    op.add_column('jobs', sa.Column('quality_score', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('is_recruiter_post', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('jobs', sa.Column('last_validated_at', sa.DateTime(), nullable=True))
    op.create_index('ix_jobs_external_id', 'jobs', ['external_id'], unique=False)
    op.create_index('ix_jobs_last_validated_at', 'jobs', ['last_validated_at'], unique=False)
    op.create_unique_constraint(None, 'jobs', ['dedup_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='unique')
    op.drop_index('ix_jobs_last_validated_at', table_name='jobs')
    op.drop_index('ix_jobs_external_id', table_name='jobs')
    op.drop_column('jobs', 'last_validated_at')
    op.drop_column('jobs', 'is_recruiter_post')
    op.drop_column('jobs', 'quality_score')
    op.drop_column('jobs', 'dedup_hash')
    op.drop_column('jobs', 'external_id')
    # ### end Alembic commands ###
