import { z } from 'zod'

export const filterSchema = z.object({
  keyword: z.string().optional(),
  location: z.string().optional(),
  workplace_type: z.array(z.string()).optional(),
  commitment: z.array(z.string()).optional(),
  experience_seniority: z.array(z.string()).optional(),
  experience_role_type: z.array(z.string()).optional(),
  experience_role_industry_min: z.number().optional(),
  experience_role_industry_max: z.number().optional(),
  experience_role_industry_exclude_missing: z.boolean().optional(),
  experience_management_min: z.number().optional(),
  experience_management_max: z.number().optional(),
  experience_management_exclude_missing: z.boolean().optional(),
  department: z.array(z.string()).optional(),
  yoe_min: z.number().optional(),
  yoe_max: z.number().optional(),
  salary_min: z.number().optional(),
  salary_minimum_min: z.string().optional(),
  salary_minimum_max: z.string().optional(),
  salary_minimum_frequency: z.string().optional(),
  salary_maximum_min: z.string().optional(),
  salary_maximum_max: z.string().optional(),
  salary_maximum_frequency: z.string().optional(),
  salary_listed_frequency: z.string().optional(),
  salary_currency: z.string().optional(),
  founding_year_min: z.number().optional(),
  founding_year_max: z.number().optional(),
  company_size: z.array(z.string()).optional(),
  benefits_perks: z.array(z.string()).optional(),
  encouraged_to_apply: z.array(z.string()).optional(),
})

export type Filters = z.infer<typeof filterSchema>
