import { z } from 'zod'

export const filterSchema = z.object({
  keyword: z.string().optional(),
  job_title_terms: z.string().optional(),
  job_title_boolean_query: z.string().optional(),
  technical_keywords_terms: z.string().optional(),
  technical_keywords_boolean_query: z.string().optional(),
  job_description_boolean_query: z.string().optional(),
  requirements_keywords_boolean_query: z.string().optional(),
  location: z.string().optional(),
  workplace_type: z.array(z.string()).optional(),
  commitment: z.array(z.string()).optional(),
  experience_seniority: z.array(z.string()).optional(),
  experience_role_type: z.array(z.string()).optional(),
  experience_role_industry_min: z.number().optional(),
  experience_role_industry_max: z.number().optional(),
  experience_role_industry_exclude_missing: z.boolean().optional(),
  experience_management_min: z.number().optional(),
  experience_management_max: z.number().optional(),
  experience_management_exclude_missing: z.boolean().optional(),
  department: z.array(z.string()).optional(),
  yoe_min: z.number().optional(),
  yoe_max: z.number().optional(),
  salary_min: z.number().optional(),
  salary_minimum_min: z.string().optional(),
  salary_minimum_max: z.string().optional(),
  salary_minimum_frequency: z.string().optional(),
  salary_maximum_min: z.string().optional(),
  salary_maximum_max: z.string().optional(),
  salary_maximum_frequency: z.string().optional(),
  salary_listed_frequency: z.string().optional(),
  salary_currency: z.string().optional(),
  shift_morning: z.enum(['required', 'optional', 'not_indicated']).optional(),
  shift_afternoon: z.enum(['required', 'optional', 'not_indicated']).optional(),
  shift_overnight: z.enum(['required', 'optional', 'not_indicated']).optional(),
  shift_weekend_availability: z.enum(['required', 'not_indicated']).optional(),
  shift_holiday_availability: z.enum(['required', 'not_indicated']).optional(),
  shift_overtime_availability: z.enum(['required', 'not_indicated']).optional(),
  shift_oncall_requirements: z
    .array(z.enum(['none', 'occasional_once_a_month_or_less', 'regular_once_a_week_or_more']))
    .optional(),
  travel_air: z.array(z.string()).optional(),
  travel_land: z.array(z.string()).optional(),
  stage_investors: z.string().optional(),
  stage_exclude_investors: z.string().optional(),
  stage_latest_round: z.string().optional(),
  stage_exclude_latest_round: z.string().optional(),
  stage_raised_in_or_after: z.number().optional(),
  stage_latest_round_amount_raised: z.number().optional(),
  company_names: z.string().optional(),
  company_exclude_names: z.string().optional(),
  company_hq_countries: z.string().optional(),
  company_exclude_hq_countries: z.string().optional(),
  industry_organization_type: z.string().optional(),
  industry_exclude_organization_types: z.string().optional(),
  industry_company_industry: z.string().optional(),
  industry_exclude_industries: z.string().optional(),
  industry_company_activities_keywords: z.string().optional(),
  industry_exclude_company_industries_keywords: z.string().optional(),
  industry_usajobs_policy: z.string().optional(),
  licenses_hide_required: z.boolean().optional(),
  licenses_keywords: z.string().optional(),
  licenses_exclude_keywords: z.string().optional(),
  education_associates_requirement: z.enum(['required', 'preferred']).optional(),
  education_bachelors_requirement: z.enum(['required', 'preferred']).optional(),
  education_masters_requirement: z.enum(['required', 'preferred']).optional(),
  education_doctorate_requirement: z.enum(['required', 'preferred']).optional(),
  security_clearance: z.array(z.string()).optional(),
  language_requirements: z.string().optional(),
  language_exclude_requirements: z.string().optional(),
  founding_year_min: z.number().optional(),
  founding_year_max: z.number().optional(),
  company_size: z.array(z.string()).optional(),
  benefits_perks: z.array(z.string()).optional(),
  encouraged_to_apply: z.array(z.string()).optional(),
})

export type Filters = z.infer<typeof filterSchema>
